In [11]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [12]:
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [13]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [14]:
x = df[['tip','sex','smoker','day','time','size']]
y = df['total_bill']

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [16]:
#Feature Encoding (label encoding and one hot encoding)
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()
x_train['sex'] = le1.fit_transform(x_train['sex'])
x_train['smoker'] = le2.fit_transform(x_train['smoker'])
x_train['time'] = le3.fit_transform(x_train['time'])
x_train

      tip  sex  smoker   day  time  size
21   2.75    0       0   Sat     0     2
45   3.00    1       0   Sun     0     2
222  1.92    1       1   Fri     1     1
56   3.00    1       1   Sat     0     4
138  2.00    1       1  Thur     1     2
..    ...  ...     ...   ...   ...   ...
137  2.00    0       0  Thur     1     2
154  2.00    1       0   Sun     0     4
128  2.00    0       0  Thur     1     2
159  2.00    1       0   Sun     0     4
157  3.75    0       0   Sun     0     4

[183 rows x 6 columns]

In [17]:
x_test['sex'] = le1.transform(x_test['sex'])
x_test['smoker'] = le2.transform(x_test['smoker'])
x_test['time'] = le3.transform(x_test['time'])
x_test

      tip  sex  smoker  day  time  size
206  3.41    1       1  Sat     0     3
109  4.00    0       1  Sat     0     2
95   4.73    1       1  Fri     0     4
63   3.76    1       1  Sat     0     4
94   3.25    0       0  Fri     0     2
..    ...  ...     ...  ...   ...   ...
7    3.12    1       0  Sun     0     4
20   4.08    1       0  Sat     0     2
47   6.00    1       0  Sun     0     4
68   2.01    1       0  Sat     0     2
15   3.92    1       0  Sun     0     2

[61 rows x 6 columns]

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

t = ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],remainder='passthrough')
x_train = t.fit_transform(x_train)
x_train

array([[1., 0., 0., ..., 0., 0., 2.],
       [0., 1., 0., ..., 0., 0., 2.],
       [0., 0., 0., ..., 1., 1., 1.],
       ...,
       [0., 0., 1., ..., 0., 1., 2.],
       [0., 1., 0., ..., 0., 0., 4.],
       [0., 1., 0., ..., 0., 0., 4.]])

In [20]:
x_test = t.transform(x_test)
x_test

array([[1.  , 0.  , 0.  , 3.41, 1.  , 1.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 4.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 4.73, 1.  , 1.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.76, 1.  , 1.  , 0.  , 4.  ],
       [0.  , 0.  , 0.  , 3.25, 0.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 3.25, 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.24, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.88, 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 5.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 3.16, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.21, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 0.  , 1.  , 1.  , 4.  ],
       [0.  , 0.  , 1.  , 4.  , 1.  , 0.  , 1.  , 4.  ],
       [0.  , 0.  , 1.  , 2.18, 1.  , 0.  , 1.  , 3.  ],
       [0.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 1.  , 0.  , 1.  , 5.  ],
       [1.  , 0.  , 0.  , 9.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 2.03, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 0.  , 1.  , 2.31, 1.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 2.34, 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.48, 0.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.5 , 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.06, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.61, 0.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 0.  , 0.  , 1.  , 6.  ],
       [1.  , 0.  , 0.  , 2.47, 0.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.25, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.45, 0.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 1.17, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 5.2 , 0.  , 0.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.23, 0.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 3.  , 1.  , 1.  , 1.  , 2.  ],
       [0.  , 0.  , 0.  , 3.  , 0.  , 0.  , 1.  , 3.  ],
       [0.  , 0.  , 1.  , 2.92, 0.  , 0.  , 1.  , 4.  ],
       [0.  , 0.  , 1.  , 5.  , 1.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 1.5 , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 5.92, 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 2.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 4.  , 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.05, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 1.57, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 2.5 , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.74, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 5.07, 1.  , 0.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 2.52, 0.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 3.35, 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 3.76, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 3.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 4.  , 0.  , 0.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 4.  , 1.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 0.  , 1.5 , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.12, 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 4.08, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 6.  , 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 2.01, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.92, 1.  , 0.  , 0.  , 2.  ]])

In [ ]:
from sklearn.svm import SVR
svr = SVR()
svr.fit(x_train,y_train)
y_pred = svr.predict(x_test)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [ ]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))